name = "rijiki-backend"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
PUBLIC_ASSET_BASE_URL = "https://pub-5f21fb1a2c4245bba64085187a0fabc7.r2.dev"

[[r2_buckets]]
binding = "PUBLIC_BUCKET"
bucket_name = "rijiki-public"

[[r2_buckets]]
binding = "PRIVATE_BUCKET"
bucket_name = "rijiki-private"